language: node_js
node_js: 10

cache:
  directories:
    - node_modules

install:
  - npm config set registry http://registry.npm.taobao.org/
  - npm cache verify
  - npm install

script:
  - npm test

branches:
  only:
    - master