language: node_js
node_js: 10

cache:
  directories:
    - node_modules

install:
  - npm install

stages:
 - test
 - name: deploy

jobs:
 include:
   - stage: test
     script:
       - node --version
       - npm --version
       - echo "Testing Started ..."
       - npm test
       - echo "Testing Finished."

   - stage: deploy
     deploy:
       provider: npm
       email: i@aiyo.xyz
       api_key: "$NPM_TOKEN"
       skip_cleanup: true
       on:
         all_branches: true